/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import config.dcConnector;
import config.session;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import pts.LoginForm;

/**
 *
 * @author desktop11
 */
public class ParkingDetails extends javax.swing.JFrame {

    /**
     * Creates new form ParkingDetails
     */
    public ParkingDetails() {
        initComponents();
        table();
        displayData();
        
        showDate();
         
         Thread t = new Thread(){
             
             public void run()
                {
                    while(true)
                    {
                        DateFormat date = new SimpleDateFormat("hh : mm : ss aa");
                        String datestring = date.format(new Date()).toString();
                        
                        time.setText(datestring);
                        
                        try{
                            Thread.sleep(1);
                        
                        }catch(Exception e){
                            
                        }
                        
                    }
                }
         };
         t.start();
    }
    
    
    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("MM-dd-yyyy");
        String dat = s.format(d);
        date.setText(dat);
        
    }

    Connection connect;
    PreparedStatement pst1;
    PreparedStatement pst2;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        AD_nm = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        date = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VDB = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        V_b = new javax.swing.JTextField();
        V_pn = new javax.swing.JTextField();
        V_at = new javax.swing.JTextField();
        V_vt = new javax.swing.JComboBox<>();
        V_add = new javax.swing.JButton();
        V_Cc = new javax.swing.JTextField();
        j5 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        V_Cn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        V_tt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        j7 = new javax.swing.JLabel();
        Ids = new javax.swing.JTextField();
        j8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        V_TO = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(2, 16, 36));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(5, 38, 89));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(193, 232, 255));
        jLabel2.setText("Welcome");

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(193, 232, 255));
        jLabel10.setText("USER");

        jPanel6.setBackground(new java.awt.Color(2, 16, 36));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AD_nm.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        AD_nm.setForeground(new java.awt.Color(193, 232, 255));
        AD_nm.setText("Welcome");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(AD_nm)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(AD_nm)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(2, 16, 36));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        date.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        date.setForeground(new java.awt.Color(193, 232, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        date.setText("Date ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(193, 232, 255));
        jLabel1.setText("Date");

        jPanel7.setBackground(new java.awt.Color(2, 16, 36));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        time.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        time.setForeground(new java.awt.Color(193, 232, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("Time ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(time))
        );

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(193, 232, 255));
        jLabel4.setText("Time");

        jLabel6.setText("Back");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)))
                .addGap(879, 879, 879)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel4)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 70));

        VDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        VDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VDBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VDB);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 990, 460));

        jPanel3.setBackground(new java.awt.Color(5, 38, 89));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        j2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j2.setForeground(new java.awt.Color(125, 160, 202));
        j2.setText("Brand");

        j3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j3.setForeground(new java.awt.Color(125, 160, 202));
        j3.setText("Plate Number");

        j4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j4.setForeground(new java.awt.Color(125, 160, 202));
        j4.setText("Time In");

        j6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j6.setForeground(new java.awt.Color(125, 160, 202));
        j6.setText("Vehicle Type");

        V_b.setBackground(new java.awt.Color(2, 16, 36));
        V_b.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_b.setForeground(new java.awt.Color(193, 232, 255));

        V_pn.setBackground(new java.awt.Color(2, 16, 36));
        V_pn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_pn.setForeground(new java.awt.Color(193, 232, 255));

        V_at.setBackground(new java.awt.Color(2, 16, 36));
        V_at.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_at.setForeground(new java.awt.Color(193, 232, 255));

        V_vt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_vt.setForeground(new java.awt.Color(193, 232, 255));
        V_vt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motorcycle", "Truck", "Van", "Bus", "Sikad" }));
        V_vt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_vtActionPerformed(evt);
            }
        });

        V_add.setBackground(new java.awt.Color(2, 16, 36));
        V_add.setText("ADD");
        V_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_addActionPerformed(evt);
            }
        });

        V_Cc.setBackground(new java.awt.Color(2, 16, 36));
        V_Cc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_Cc.setForeground(new java.awt.Color(193, 232, 255));
        V_Cc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_CcActionPerformed(evt);
            }
        });

        j5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j5.setForeground(new java.awt.Color(125, 160, 202));
        j5.setText("Color");

        j1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j1.setForeground(new java.awt.Color(125, 160, 202));
        j1.setText("Company Name");

        V_Cn.setBackground(new java.awt.Color(2, 16, 36));
        V_Cn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_Cn.setForeground(new java.awt.Color(193, 232, 255));

        jButton1.setBackground(new java.awt.Color(2, 16, 36));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(2, 16, 36));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(125, 160, 202));
        jLabel3.setText("Ticket No");

        V_tt.setBackground(new java.awt.Color(2, 16, 36));
        V_tt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_tt.setForeground(new java.awt.Color(193, 232, 255));

        jButton3.setBackground(new java.awt.Color(2, 16, 36));
        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        j7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j7.setForeground(new java.awt.Color(125, 160, 202));
        j7.setText("ID");

        Ids.setBackground(new java.awt.Color(2, 16, 36));
        Ids.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Ids.setForeground(new java.awt.Color(193, 232, 255));
        Ids.setEnabled(false);

        j8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j8.setForeground(new java.awt.Color(125, 160, 202));
        j8.setText("Date");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(125, 160, 202));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Time Out");

        V_TO.setBackground(new java.awt.Color(2, 16, 36));
        V_TO.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        V_TO.setForeground(new java.awt.Color(193, 232, 255));

        jButton4.setBackground(new java.awt.Color(2, 16, 36));
        jButton4.setText("Ticket");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(j5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(j8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(V_b)
                                    .addComponent(V_vt, 0, 153, Short.MAX_VALUE)
                                    .addComponent(V_Cc)
                                    .addComponent(V_at)
                                    .addComponent(V_pn)
                                    .addComponent(V_tt)
                                    .addComponent(V_Cn)
                                    .addComponent(Ids, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(V_TO)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(V_add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)))
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(j7, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                        .addGap(248, 248, 248))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1)
                    .addComponent(V_Cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(V_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2)
                    .addComponent(V_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j3)
                    .addComponent(V_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4)
                    .addComponent(V_at, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j5)
                    .addComponent(V_Cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j6)
                    .addComponent(V_vt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(j8)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(V_TO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(V_add)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(79, 79, 79))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 310, 540));

        jPanel4.setBackground(new java.awt.Color(2, 16, 36));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 1300, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     public void displayData() {
        try {
            dcConnector dbc = new dcConnector();
            ResultSet rs = dbc.getData("SELECT ID, TicketNo, Companyname , Brand , PlateNo, TimeIn ,TimeOut , Color , VehicleType , Date FROM parking");
            VDB.setModel(DbUtils.resultSetToTableModel(rs));
            rs.close();
        } catch (SQLException ex) {
            System.out.println("Errors: " + ex.getMessage());
        }
    }
    
    
     
     public void table() {
     int rowIndex = VDB.getSelectedRow();
        if (rowIndex != -1) { // Check if a row is selected
            try {
                dcConnector dc = new dcConnector();
                TableModel tbl = VDB.getModel();
                // Assuming you have a way to identify the selected row uniquely, e.g., by TicketNo
                String selectedTicketNo = tbl.getValueAt(rowIndex, 1).toString(); // Assuming TicketNo is at index 1

                ResultSet Rs = dc.getData("SELECT TicketNo, Companyname, PlateNo, TimeIn, TimeOut, Date, Color, Brand, VehicleType FROM parking WHERE TicketNo = " + selectedTicketNo);

                DefaultTableModel df = (DefaultTableModel) VDB.getModel();
                df.setRowCount(0); // Clear existing rows

                while (Rs.next()) {
                    Vector<String> row = new Vector<>();
                    row.add(String.valueOf(Rs.getInt("TicketNo")));
                    row.add(Rs.getString("Companyname"));
                    row.add(Rs.getString("PlateNo"));
                    row.add(Rs.getString("TimeIn"));
                    row.add(Rs.getString("Date"));
                    row.add(Rs.getString("TimeOut"));
                    row.add(Rs.getString("Color"));
                    row.add(Rs.getString("Brand"));
                    row.add(Rs.getString("VehicleType"));
                    df.addRow(row);
                }
                Rs.close();
            } catch (SQLException ex) {
                System.out.println("Errors: " + ex.getMessage());
            }
        } else {
            // Handle the case when no row is selected
            System.out.println("No row is selected.");
        }
   } 
     
    
    
    private void VDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VDBMouseClicked
       int selectedRow = VDB.getSelectedRow();

        if (selectedRow != -1) { // Check if a row is selected
            // Set text fields from the table values
            Ids.setText(VDB.getValueAt(selectedRow, 0).toString());
            V_tt.setText(VDB.getValueAt(selectedRow, 1).toString());
            V_Cn.setText(VDB.getValueAt(selectedRow, 2).toString());
            V_b.setText(VDB.getValueAt(selectedRow, 3).toString());
            V_pn.setText(VDB.getValueAt(selectedRow, 4).toString());
            V_at.setText(VDB.getValueAt(selectedRow, 5).toString());
            V_TO.setText(VDB.getValueAt(selectedRow, 6).toString()); // Assuming timeout is in the 7th column (index 6)
            V_Cc.setText(VDB.getValueAt(selectedRow, 7).toString());
            V_vt.setSelectedItem(VDB.getValueAt(selectedRow, 8).toString());

            // Parse and set the date
            try {
                String dateString = VDB.getValueAt(selectedRow, 9).toString(); // Assuming the date is in the 10th column (index 9)
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                Date date = sdf.parse(dateString);
                jDateChooser1.setDate(date);
            } catch (ParseException ex) {
                ex.printStackTrace();
                jDateChooser1.setDate(null); // Clear date if any error occurs
            }
        }
    }//GEN-LAST:event_VDBMouseClicked

    private void V_vtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_vtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V_vtActionPerformed

    private void V_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_addActionPerformed
String Tt = V_tt.getText();   //1
    String Cn = V_Cn.getText();
    String Br = V_b.getText();
    String Pn = V_pn.getText();
    String At = V_at.getText();
    String TO = V_TO.getText(); // New field for Timeout
    String C = V_Cc.getText();
    String Vt = V_vt.getSelectedItem().toString();

    // Check if all fields are filled
    if (Tt.isEmpty() || Cn.isEmpty() || Br.isEmpty() || Pn.isEmpty() || At.isEmpty() || TO.isEmpty() || C.isEmpty() || Vt.isEmpty() || jDateChooser1.getDate() == null) {
        JOptionPane.showMessageDialog(null, "Please fill in all the details.");
        return;
    }

    // Get the selected date from jDateChooser1 and format it
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String selectedDate = sdf.format(jDateChooser1.getDate());

    try {
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");

        // Check if the car (PlateNo) already exists in the database
        String checkQuery = "SELECT COUNT(*) FROM parking WHERE PlateNo = ?";
        PreparedStatement checkPst = connect.prepareStatement(checkQuery);
        checkPst.setString(1, Pn);
        ResultSet rs = checkPst.executeQuery();
        if (rs.next() && rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(null, "Car with PlateNo " + Pn + " already exists! ");
            return;
        }

        // Insert data into the database
        String query = "INSERT INTO parking (TicketNo, Companyname, Brand, PlateNo, TimeIn, Timeout, Color, VehicleType, Date) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = connect.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, Tt);
        pst.setString(2, Cn);
        pst.setString(3, Br);
        pst.setString(4, Pn);
        pst.setString(5, At);
        pst.setString(6, TO); // Add Timeout
        pst.setString(7, C);
        pst.setString(8, Vt);
        pst.setString(9, selectedDate); // Set the selected date
        pst.executeUpdate();

        // Get the auto-generated ID
        ResultSet generatedKeys = pst.getGeneratedKeys();
        if (generatedKeys.next()) {
            int id = generatedKeys.getInt(1);
            // Update the table with the new entry
            DefaultTableModel model = (DefaultTableModel) VDB.getModel();
            model.addRow(new Object[]{id, Tt, Cn, Br, Pn, At, TO, C, Vt, selectedDate}); // Ensure the correct order of values
        }
        JOptionPane.showMessageDialog(null, "Details added successfully!");
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error adding details to the database.");
    }

    }//GEN-LAST:event_V_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String id = Ids.getText();
        String Tt = V_tt.getText();
        String Cn = V_Cn.getText();
        String Br = V_b.getText();
        String Pn = V_pn.getText();
        String At = V_at.getText();
        String To = V_TO.getText();  // Get the Timeout value
        String C = V_Cc.getText();
        String Vt = V_vt.getSelectedItem().toString();

        // Check if all fields are filled
        if (id.isEmpty() || Tt.isEmpty() || Cn.isEmpty() || Br.isEmpty() || Pn.isEmpty() || At.isEmpty() || To.isEmpty() || C.isEmpty() || Vt.isEmpty() || jDateChooser1.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Please fill in all the details.");
        } else {
            try {
                // Initialize the database connection
                Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");

                // Format the selected date from jDateChooser1
                SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                String selectedDate = sdf.format(jDateChooser1.getDate());

                // Update data in the database
                String query = "UPDATE parking SET TicketNo = ?, Companyname = ?, Brand = ?, PlateNo = ?, TimeIn = ?, Timeout = ?, Color = ?, VehicleType = ?, Date = ? WHERE ID = ?";
                PreparedStatement pst = connect.prepareStatement(query);
                pst.setString(1, Tt);
                pst.setString(2, Cn);
                pst.setString(3, Br);
                pst.setString(4, Pn);
                pst.setString(5, At);
                pst.setString(6, To); // Set the Timeout
                pst.setString(7, C); // Set the color
                pst.setString(8, Vt);
                pst.setString(9, selectedDate); // Set the selected date
                pst.setString(10, id);
                pst.executeUpdate();

                // Update the table model
                DefaultTableModel model = (DefaultTableModel) VDB.getModel();
                int selectedRow = VDB.getSelectedRow();
                model.setValueAt(id, selectedRow, 0);
                model.setValueAt(Tt, selectedRow, 1);
                model.setValueAt(Cn, selectedRow, 2);
                model.setValueAt(Br, selectedRow, 3);
                model.setValueAt(Pn, selectedRow, 4);
                model.setValueAt(At, selectedRow, 5);
                model.setValueAt(To, selectedRow, 6); // Update the Timeout in the table
                model.setValueAt(C, selectedRow, 7); // Update the color in the table
                model.setValueAt(Vt, selectedRow, 8);
                model.setValueAt(selectedDate, selectedRow, 9); // Update the date in the table

                JOptionPane.showMessageDialog(null, "Details updated successfully!");
            } catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error updating details in the database.");
            }
        }
    

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = VDB.getSelectedRow();
        if (selectedRow != -1) {
            // Confirm the deletion
            int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this entry?", "Confirm Deletion", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                try {
                    // Get the unique identifier from the selected row
                    String id = VDB.getValueAt(selectedRow, 0).toString();

                    // Remove the row from the table model
                    DefaultTableModel model = (DefaultTableModel) VDB.getModel();
                    model.removeRow(selectedRow);

                    // Connect to the database
                    Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");
                    String query = "DELETE FROM parking WHERE ID = ?";
                    PreparedStatement pst = connect.prepareStatement(query);
                    pst.setString(1, id);

                    // Execute the delete statement
                    int rowsAffected = pst.executeUpdate();

                    // Check if the deletion was successful
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Entry deleted successfully!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Error: Entry not found in the database.");
                    }

                    // Close the resources
                    pst.close();
                    connect.close();
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error deleting entry from the database.");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to delete.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        // Clear all fields
        Ids.setText("");
        V_tt.setText("");
        V_Cn.setText("");
        V_b.setText("");
        V_pn.setText("");
        V_at.setText("");
        V_Cc.setText("");
        jDateChooser1.setDate(null); // Clear the selected date
        V_vt.setSelectedIndex(0);
        V_TO.setText(""); // Clear the timeout field

    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      session sess = session.getInstance();
        
        if (sess.getId() == 0){
                
            JOptionPane.showMessageDialog(null, "Login First ");
            LoginForm lf = new LoginForm();
            lf.setVisible(true);
            this.dispose();
            
        }else{
            
                    AD_nm.setText(""+sess.getName());
                    /*AD_ln.setText(""+sess.getLname());
                    AD_em.setText(""+sess.getEmail());
                    AD_adress.setText(""+sess.getAddress());*/
        }
    }//GEN-LAST:event_formWindowActivated

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Ticket tic = new Ticket();
        tic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        UserDash ud = new UserDash();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void V_CcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_CcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V_CcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ParkingDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AD_nm;
    public javax.swing.JTextField Ids;
    private javax.swing.JTable VDB;
    private javax.swing.JTextField V_Cc;
    private javax.swing.JTextField V_Cn;
    private javax.swing.JTextField V_TO;
    private javax.swing.JButton V_add;
    private javax.swing.JTextField V_at;
    private javax.swing.JTextField V_b;
    private javax.swing.JTextField V_pn;
    private javax.swing.JTextField V_tt;
    private javax.swing.JComboBox<String> V_vt;
    private javax.swing.JLabel date;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
